### ISSUE TITLE
换了训练样本就报这个错，大佬能解答一下么 IndexError: row index (1836) out of range

### ISSUE THREAD

**Issue by NewCrazyStone** [Coldwave96/MaliciousUrls_Part2#2]
![image](https://user-images.githubusercontent.com/24403973/156138674-6f5872c9-92ce-492d-ac60-122a9a18b1a1.png)
`Traceback (most recent call last):
  File "D:\PycharmProjects\MaliciousUrls_Part2\start.py", line 44, in <module>
    r = a.Train()
  File "D:\PycharmProjects\MaliciousUrls_Part2\model.py", line 88, in Train
    X = self.transform(self.kmeans(X))
  File "D:\PycharmProjects\MaliciousUrls_Part2\model.py", line 167, in transform
    temp = weight[j].rows[0]
  File "D:\PycharmProjects\MaliciousUrls_Part2\venv\lib\site-packages\scipy\sparse\_lil.py", line 211, in __getitem__
    return IndexMixin.__getitem__(self, key)
  File "D:\PycharmProjects\MaliciousUrls_Part2\venv\lib\site-packages\scipy\sparse\_index.py", line 47, in __getitem__
    row, col = self._validate_indices(key)
  File "D:\PycharmProjects\MaliciousUrls_Part2\venv\lib\site-packages\scipy\sparse\_index.py", line 155, in _validate_indices
    raise IndexError('row index (%d) out of range' % row)
IndexError: row index (1836) out of range`

**Comment by NewCrazyStone** [comment]
是不是我训练样本的数量太少了还是怎么了

**Comment by Coldwave96** [comment]
我是在model文件夹里预设好了模型，所以你更换了训练样本需要重新训练新的模型。如果还是用默认的模型就会造成特征不一致报错。你现在只是更换了样本而没有训练新模型，所以报错。

**Comment by NewCrazyStone** [comment]
这个是训练新模型的时候报错了，不是预测的时候报错

**Comment by NewCrazyStone** [comment]
我换了样本，要训练新模型，训练的时候报错了

**Comment by NewCrazyStone** [comment]
![image](https://user-images.githubusercontent.com/24403973/156143425-189d2a67-dd94-4340-a631-5c5db76840ba.png)
![image](https://user-images.githubusercontent.com/24403973/156143532-40a21f0a-5c1a-4646-a967-44d6020c9e99.png)
